// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';
import node from '@astrojs/node';
import compressor from 'astro-compressor';

// https://astro.build/config
export default defineConfig({
  site: 'https://herzblatt-journal.com',
  adapter: node({ mode: 'standalone' }),
  integrations: [compressor({ gzip: true, brotli: true }), sitemap({
    filter: (page) =>
      !page.match(/\/blog\/\d+/) &&
      !page.includes('/404') &&
      !page.includes('/suche') &&
      !page.includes('/quiz') &&
      !page.includes('/dating-typ-test'),
    changefreq: 'weekly',
    lastmod: new Date(),
  })],
  redirects: {
    // Existing redirects
    '/review/michverlieben': { status: 301, destination: '/blog/michverlieben-test-erfahrungen' },
    '/review/onlydates69': { status: 301, destination: '/blog/onlydates69-test-erfahrungen' },
    '/review/sex69': { status: 301, destination: '/blog/sex69-test-erfahrungen' },
    '/review/single69': { status: 301, destination: '/blog/single69-test-erfahrungen' },
    '/review/singles69': { status: 301, destination: '/blog/single69-test-erfahrungen' },
    '/review/whatsmeet': { status: 301, destination: '/blog/whatsmeet-test-erfahrungen' },
    '/review/xloves': { status: 301, destination: '/blog/xloves-test-erfahrungen' },
    '/review/i-loves': { status: 301, destination: '/blog/i-loves-test-erfahrungen' },
    '/blog/dating-mit-kindern': { status: 301, destination: '/blog/dating-mit-kind' },
    '/blog/online-dating-sicherheit-tipps': { status: 301, destination: '/blog/online-dating-sicherheit' },
    '/blog/selbstbewusstsein-staerken': { status: 301, destination: '/blog/selbstakzeptanz-dating-erfolg' },

    // Duplikate zusammengefuehrt (2026-03-24)
    '/blog/kennenlernen-fragen-date': { status: 301, destination: '/blog/dating-fragen-kennenlernen' },
    '/blog/dating-als-alleinerziehend-tipps': { status: 301, destination: '/blog/dating-mit-kindern-patchwork' },
    '/blog/dating-mit-chronischer-krankheit': { status: 301, destination: '/blog/dating-mit-krankheit-chronisch' },
    '/blog/dating-als-schuechterne-frau': { status: 301, destination: '/blog/dating-tipps-fuer-schuechterne-frauen' },
    '/blog/beziehung-emotionale-intelligenz': { status: 301, destination: '/blog/emotionale-intelligenz-beziehung' },
    '/blog/emotionale-intelligenz-beziehung-entwickeln': { status: 301, destination: '/blog/emotionale-intelligenz-beziehung' },
    '/blog/erste-beziehung-ratgeber': { status: 301, destination: '/blog/erste-beziehung-tipps-guide' },
    '/blog/gaslighting-erkennen-beziehung-guide': { status: 301, destination: '/blog/gaslighting-beziehung' },
    '/blog/inneres-kind-heilen-beziehung': { status: 301, destination: '/blog/inner-child-beziehung' },
    '/blog/beziehung-introvertiert-extrovertiert-paar': { status: 301, destination: '/blog/dating-introvertiert-extrovertiert-paar-guide' },
    '/blog/lovebombing-erkennen-schuetzen': { status: 301, destination: '/blog/love-bombing-erkennen-schuetzen' },
    '/blog/partner-mit-depression-unterstuetzen': { status: 301, destination: '/blog/partner-depression-unterstuetzen-guide' },
    '/blog/beziehung-toxische-schwiegereltern': { status: 301, destination: '/blog/beziehung-toxische-schwiegereltern-umgang' },
    '/blog/beziehung-unterschiedliche-libido': { status: 301, destination: '/blog/beziehung-unterschiedliche-libido-loesungen' },
    '/blog/verlustangst-beziehung': { status: 301, destination: '/blog/verlustangst-beziehung-ueberwinden' },
    '/blog/beziehung-zusammenziehen-richtige-zeitpunkt': { status: 301, destination: '/blog/zusammenziehen-oder-nicht' },
    '/blog/beziehung-staerken-5-sprachen-der-liebe': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/blog/love-languages-beziehung': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/blog/love-languages-komplett-guide': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/blog/liebessprachen-test-anleitung': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/blog/beziehung-eifersucht-ueberwinden': { status: 301, destination: '/blog/beziehung-und-eifersucht-ueberwinden' },
    '/blog/eifersucht-ueberwinden-tipps': { status: 301, destination: '/blog/beziehung-und-eifersucht-ueberwinden' },
    '/blog/beziehung-streit-richtig': { status: 301, destination: '/blog/streit-beziehung-richtig-loesen' },
    '/blog/zusammenziehen-tipps': { status: 301, destination: '/blog/zusammenziehen-oder-nicht' },
    '/blog/zusammenziehen-wann-richtig': { status: 301, destination: '/blog/zusammenziehen-oder-nicht' },
    '/blog/beziehung-nach-trennung-freunde-bleiben': { status: 301, destination: '/blog/freundschaft-nach-trennung' },
    '/blog/trennung-freundschaft-bleiben': { status: 301, destination: '/blog/freundschaft-nach-trennung' },
    '/blog/dating-burnout-recovery': { status: 301, destination: '/blog/dating-nach-burnout' },
    '/blog/dating-burnout': { status: 301, destination: '/blog/dating-nach-burnout' },
    '/blog/catfishing-online-dating-schutz': { status: 301, destination: '/blog/catfishing-erkennen-schuetzen' },
    '/blog/date-ideen-fuer-jede-situation': { status: 301, destination: '/blog/date-ideen-komplett-sammlung' },
    '/blog/date-ideen-nach-budget': { status: 301, destination: '/blog/date-ideen-komplett-sammlung' },
    '/blog/emotionale-intelligenz-dating': { status: 301, destination: '/blog/emotionale-intelligenz-beziehung' },
    '/blog/emotionale-intelligenz-verbessern': { status: 301, destination: '/blog/emotionale-intelligenz-beziehung' },
    '/blog/erste-beziehung-tipps': { status: 301, destination: '/blog/erste-beziehung-tipps-guide' },
    '/blog/dating-introvertiert-extrovertiert': { status: 301, destination: '/blog/dating-introvertiert-extrovertiert-paar-guide' },
    '/blog/beziehung-introvertiert-extrovertiert': { status: 301, destination: '/blog/dating-introvertiert-extrovertiert-paar-guide' },
    // Cannibalization consolidation (82 redirects)
    '/blog/attachment-styles-dating': { status: 301, destination: '/blog/attachment-styles-guide' },
    '/blog/beste-dating-apps-2026': { status: 301, destination: '/blog/dating-app-vergleich-2026' },
    '/blog/beziehung-eifersucht-typen': { status: 301, destination: '/blog/eifersucht-bekaempfen' },
    '/blog/beziehung-kommunikations-guide': { status: 301, destination: '/blog/kommunikation-beziehung' },
    '/blog/beziehung-kommunikationsfehler': { status: 301, destination: '/blog/kommunikation-beziehung' },
    '/blog/beziehung-langzeit-vertrauen': { status: 301, destination: '/blog/vertrauen-aufbauen-beziehung' },
    '/blog/beziehung-liebe-sprachen-zeigen': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/blog/beziehung-love-language-aktivitaeten': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/blog/beziehung-streit-deeskalation': { status: 301, destination: '/blog/beziehung-streit-guide' },
    '/blog/beziehung-streitkultur': { status: 301, destination: '/blog/beziehung-streit-guide' },
    '/blog/beziehung-vertrauen-wieder-aufbauen': { status: 301, destination: '/blog/vertrauen-aufbauen-beziehung' },
    '/blog/dating-als-introvertierter-mann': { status: 301, destination: '/blog/introvertiert-dating' },
    '/blog/dating-app-opener-guide': { status: 301, destination: '/blog/erste-nachricht-dating-app' },
    '/blog/dating-apps-vergleich': { status: 301, destination: '/blog/dating-app-vergleich-2026' },
    '/blog/dating-authentische-profilbeschreibung': { status: 301, destination: '/blog/online-dating-profiltext' },
    '/blog/dating-do-dont-guide': { status: 301, destination: '/blog/dating-fehler-frauen' },
    '/blog/dating-erste-nachricht': { status: 301, destination: '/blog/erste-nachricht-dating-app' },
    '/blog/dating-erste-nachricht-psychologie': { status: 301, destination: '/blog/erste-nachricht-dating-app' },
    '/blog/dating-fatigue-ueberwinden': { status: 301, destination: '/blog/dating-nach-burnout' },
    '/blog/dating-fehler-maenner': { status: 301, destination: '/blog/dating-fehler-frauen' },
    '/blog/dating-fotografie-tipps': { status: 301, destination: '/blog/dating-profile-fotos-tipps' },
    '/blog/dating-fruehwarnzeichen': { status: 301, destination: '/blog/dating-red-flags-maenner-erkennen' },
    '/blog/dating-fuer-introvertierte': { status: 301, destination: '/blog/introvertiert-dating' },
    '/blog/dating-ghosting-recovery': { status: 301, destination: '/blog/ghosting-umgehen-tipps' },
    '/blog/dating-introvertierte': { status: 301, destination: '/blog/introvertiert-dating' },
    '/blog/dating-koerpersprache-fehler': { status: 301, destination: '/blog/koerpersprache-deuten' },
    '/blog/dating-koerpersprache-lesen': { status: 301, destination: '/blog/koerpersprache-deuten' },
    '/blog/dating-nach-40-maenner': { status: 301, destination: '/blog/dating-ab-40' },
    '/blog/dating-nach-40-neustart': { status: 301, destination: '/blog/dating-ab-40' },
    '/blog/dating-nach-ghosting-erfahrung': { status: 301, destination: '/blog/ghosting-umgehen-tipps' },
    '/blog/dating-nach-langzeitbeziehung': { status: 301, destination: '/blog/dating-nach-trennung' },
    '/blog/dating-nach-narzissmus-erfahrung': { status: 301, destination: '/blog/dating-nach-narzisst' },
    '/blog/dating-nach-toxischer-beziehung': { status: 301, destination: '/blog/dating-nach-narzisst' },
    '/blog/dating-nach-trennung-timeline': { status: 301, destination: '/blog/dating-nach-trennung' },
    '/blog/dating-nach-trennung-wann-bereit': { status: 301, destination: '/blog/dating-nach-trennung' },
    '/blog/dating-profil-optimierung': { status: 301, destination: '/blog/online-dating-profiltext' },
    '/blog/dating-profilfotos-fehler': { status: 301, destination: '/blog/dating-profile-fotos-tipps' },
    '/blog/dating-red-flags-maenner': { status: 301, destination: '/blog/dating-red-flags-maenner-erkennen' },
    '/blog/dating-second-date-plan': { status: 301, destination: '/blog/zweites-date-tipps' },
    // 404 Tag-Seiten -> Redirect zu Tag-Uebersicht
    '/blog/dating-texting-regeln': { status: 301, destination: '/blog/texting-regeln-dating' },
    '/blog/dating-ueber-40': { status: 301, destination: '/blog/dating-ab-40' },
    '/blog/dating-ueber-whatsapp': { status: 301, destination: '/blog/texting-regeln-dating' },
    '/blog/dating-unterschiedliche-bindungsstile': { status: 301, destination: '/blog/attachment-styles-guide' },
    '/blog/dating-vorbereitung-erste-treffen': { status: 301, destination: '/blog/erstes-date-tipps' },
    '/blog/dating-warnsignale-checkliste': { status: 301, destination: '/blog/dating-red-flags-maenner-erkennen' },
    '/blog/digitale-eifersucht': { status: 301, destination: '/blog/eifersucht-bekaempfen' },
    '/blog/eifersucht-beziehung-ueberwinden': { status: 301, destination: '/blog/eifersucht-bekaempfen' },
    '/blog/erste-nachricht-online-dating': { status: 301, destination: '/blog/erste-nachricht-dating-app' },
    '/blog/erstes-date-checkliste': { status: 301, destination: '/blog/erstes-date-tipps' },
    '/blog/erstes-date-gespraeche-fuehren': { status: 301, destination: '/blog/erstes-date-tipps' },
    '/blog/erstes-date-gespraechsthemen': { status: 301, destination: '/blog/erstes-date-tipps' },
    '/blog/erstes-date-outfit': { status: 301, destination: '/blog/erstes-date-tipps' },
    '/blog/fernbeziehung-survival-guide': { status: 301, destination: '/blog/fernbeziehung-tipps' },
    '/blog/flirt-signale-mann-frau': { status: 301, destination: '/blog/koerpersprache-deuten' },
    '/blog/introvertiert-dating-guide': { status: 301, destination: '/blog/introvertiert-dating' },
    '/blog/koerpersprache-flirten': { status: 301, destination: '/blog/koerpersprache-deuten' },
    '/blog/liebe-auf-distanz-tipps': { status: 301, destination: '/blog/fernbeziehung-tipps' },
    '/blog/long-distance-beziehung': { status: 301, destination: '/blog/fernbeziehung-tipps' },
    '/blog/long-distance-date-ideen': { status: 301, destination: '/blog/fernbeziehung-tipps' },
    '/blog/love-languages-test': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/blog/online-dating-fehler': { status: 301, destination: '/blog/dating-fehler-frauen' },
    '/blog/online-dating-fotos': { status: 301, destination: '/blog/dating-profile-fotos-tipps' },
    '/blog/online-dating-muedigkeit': { status: 301, destination: '/blog/dating-nach-burnout' },
    '/blog/online-dating-muedigkeit-ueberwinden': { status: 301, destination: '/blog/dating-nach-burnout' },
    '/blog/paarkommunikation-verbessern': { status: 301, destination: '/blog/kommunikation-beziehung' },
    '/blog/perfektes-dating-profil': { status: 301, destination: '/blog/online-dating-profiltext' },
    '/blog/richtig-streiten-beziehung': { status: 301, destination: '/blog/beziehung-streit-guide' },
    '/blog/selbstkenntnis-besseres-dating': { status: 301, destination: '/blog/selbstliebe-dating' },
    '/blog/selbstliebe-vor-partnersuche': { status: 301, destination: '/blog/selbstliebe-dating' },
    '/blog/single-leben-geniessen': { status: 301, destination: '/blog/single-gluecklich-sein' },
    '/blog/single-sein-vorteile': { status: 301, destination: '/blog/single-gluecklich-sein' },
    '/blog/singles-gluecklich': { status: 301, destination: '/blog/single-gluecklich-sein' },
    '/blog/situationship-erkennen': { status: 301, destination: '/blog/situationship-guide' },
    '/blog/situationship-erkennen-handeln': { status: 301, destination: '/blog/situationship-guide' },
    '/blog/slow-dating-trend': { status: 301, destination: '/blog/slow-dating-guide' },
    '/blog/slow-dating-trend-achtsamkeit': { status: 301, destination: '/blog/slow-dating-guide' },
    '/blog/streiten-aber-richtig': { status: 301, destination: '/blog/beziehung-streit-guide' },
    '/blog/dating-app-muedigkeit': { status: 301, destination: '/blog/dating-nach-burnout' },
    '/blog/dating-bei-social-anxiety': { status: 301, destination: '/blog/dating-angst-ueberwinden' },
    '/blog/green-flags-beziehung': { status: 301, destination: '/blog/dating-green-flags-guide' },
    '/blog/online-dating-fatigue-bekaempfen': { status: 301, destination: '/blog/dating-nach-burnout' },
    '/blog/toxische-beziehung-checkliste': { status: 301, destination: '/blog/toxische-beziehung-erkennen' },
    '/blog/toxische-dating-muster': { status: 301, destination: '/blog/toxische-beziehung-erkennen' },
    '/blog/toxische-dating-muster-durchbrechen': { status: 301, destination: '/blog/toxische-beziehung-erkennen' },
    '/blog/vertrauen-nach-betrug': { status: 301, destination: '/blog/vertrauen-aufbauen-beziehung' },
    '/blog/zweites-date-planen': { status: 301, destination: '/blog/zweites-date-tipps' },
    // Keyword cannibalization fix (2026-04-01)
    '/blog/freundschaftszone-entkommen': { status: 301, destination: '/blog/friendzone-entkommen-guide' },
    '/blog/red-flags-erkennen': { status: 301, destination: '/blog/dating-red-flags-maenner-erkennen' },
    '/blog/dating-red-flags-komplett-guide': { status: 301, destination: '/blog/dating-red-flags-maenner-erkennen' },
    '/blog/dating-red-flags-erkennen-liste': { status: 301, destination: '/blog/dating-red-flags-maenner-erkennen' },
    // Cannibalization fix round 2 (2026-04-01)
    '/blog/bindungsangst-erkennen-ueberwinden': { status: 301, destination: '/blog/bindungsangst-komplett-guide' },
    '/blog/bindungsangst-erkennen': { status: 301, destination: '/blog/bindungsangst-komplett-guide' },
    '/blog/bindungsangst-ueberwinden': { status: 301, destination: '/blog/bindungsangst-komplett-guide' },
    '/blog/bindungsangst-ueberwinden-guide': { status: 301, destination: '/blog/bindungsangst-komplett-guide' },
    '/blog/liebeskummer-komplett-ratgeber': { status: 301, destination: '/blog/liebeskummer-phasen-komplett' },
    '/blog/offene-beziehung-regeln': { status: 301, destination: '/blog/offene-beziehung-regeln-guide' },
    '/blog/beziehung-retten-12-schritte': { status: 301, destination: '/blog/beziehung-retten-kompletter-guide' },
    '/blog/beziehung-retten': { status: 301, destination: '/blog/beziehung-retten-kompletter-guide' },
    '/blog/beziehung-retten-ultimativer-guide': { status: 301, destination: '/blog/beziehung-retten-kompletter-guide' },
    '/blog/on-off-beziehung-raus-aus-kreislauf': { status: 301, destination: '/blog/on-off-beziehung-beenden' },
    '/blog/fremdgehen-verzeihen': { status: 301, destination: '/blog/fremdgehen-verzeihen-kompletter-guide' },
    // Missing /blog/ prefix redirects (from Ahrefs 404 report)
    '/vertrauen-aufbauen-beziehung': { status: 301, destination: '/blog/vertrauen-aufbauen-beziehung' },
    '/beziehung-auffrischen-ideen': { status: 301, destination: '/blog/beziehung-auffrischen-ideen' },
    '/grenzen-setzen-beziehung': { status: 301, destination: '/blog/grenzen-setzen-beziehung' },
    '/schmetterlinge-im-bauch-bedeutung': { status: 301, destination: '/blog/schmetterlinge-im-bauch-bedeutung' },
    '/beziehung-kommunikation': { status: 301, destination: '/blog/beziehung-offene-kommunikation' },
    '/richtig-streiten-beziehung': { status: 301, destination: '/blog/beziehung-streit-guide' },
    '/digitale-grenzen': { status: 301, destination: '/blog/eifersucht-bekaempfen' },
    '/beziehung-social-media': { status: 301, destination: '/blog/beziehung-social-media' },
    '/toxische-beziehung-erkennen': { status: 301, destination: '/blog/toxische-beziehung-erkennen' },
    '/stonewalling-beziehung': { status: 301, destination: '/blog/stonewalling-beziehung' },
    '/selbstliebe-partnersuche': { status: 301, destination: '/blog/selbstliebe-dating' },
    '/selbstliebe-grenzen': { status: 301, destination: '/blog/selbstliebe-nach-trennung' },
    '/selbstliebe-dating': { status: 301, destination: '/blog/selbstliebe-dating' },
    '/schwierige-gespraeche': { status: 301, destination: '/blog/schwierige-gespraeche-beziehung' },
    '/queer-dating-guide': { status: 301, destination: '/blog/queeres-dating-guide' },
    '/privatsphaere-beziehung-guide': { status: 301, destination: '/blog/privatsphaere-beziehung-guide' },
    '/polyamorie-guide': { status: 301, destination: '/blog/polyamorie-guide' },
    '/partner-finden-ohne-dating-apps': { status: 301, destination: '/blog/partner-finden-ohne-dating-apps' },
    '/paartherapie-wann-sinnvoll': { status: 301, destination: '/blog/paartherapie-wann-sinnvoll' },
    '/online-dating-sicherheit': { status: 301, destination: '/blog/online-dating-sicherheit' },
    '/manipulative-beziehung': { status: 301, destination: '/blog/manipulation-in-beziehungen' },
    '/love-languages-beziehung': { status: 301, destination: '/blog/liebessprachen-komplett-guide' },
    '/liebe-oder-gewohnheit-test': { status: 301, destination: '/blog/liebe-oder-gewohnheit-test' },
    '/vertrauen-wiederaufbauen': { status: 301, destination: '/blog/vertrauen-wieder-aufbauen-nach-luege' },
    '/vertrauen-beziehung-guide': { status: 301, destination: '/blog/erste-beziehung-tipps-guide' },
    '/trauma-verarbeitung': { status: 301, destination: '/blog/trennung-verarbeiten-neuanfang' },
    '/toxische-beziehung-guide': { status: 301, destination: '/blog/toxische-beziehung-komplett-guide' },
    '/werte-basiertes-dating': { status: 301, destination: '/blog/werte-basiertes-dating' },
    // Duplicate title redirects
    '/blog/beziehungspause-sinnvoll-regeln': { status: 301, destination: '/blog/beziehungspause-sinnvoll' },
    '/blog/dating-als-alleinerziehend': { status: 301, destination: '/blog/dating-alleinerziehend-kompletter-leitfaden' },
    '/blog/dating-als-introvertierter-mann-guide': { status: 301, destination: '/blog/dating-introvertierte-maenner' },
    '/blog/dating-als-schuechterne-frau': { status: 301, destination: '/blog/dating-tipps-fuer-schuechterne-frauen' },
    '/blog/ghosting-umgehen': { status: 301, destination: '/blog/ghosting-komplett-guide' },
    '/blog/dating-introvertiert-extrovertiert': { status: 301, destination: '/blog/dating-introvertiert-extrovertiert-paar-guide' },
  },
  compressHTML: true,
  build: {
    inlineStylesheets: 'auto',
  },
  vite: {
    plugins: [tailwindcss()],
    build: {
      cssMinify: true,
      rollupOptions: {
        output: {
          manualChunks: undefined,
        },
      },
    },
  },
});
