#!/usr/bin/env python3
"""Consolidate 1018 tags down to ~35 core categories across all blog articles."""

import os
import re
import yaml

# Master tag mapping: old_tag -> new_tag
# Tags not listed here that have count >= 5 will be kept as-is if they're in KEEP_TAGS
# Everything else maps to the closest core tag

TAG_MAP = {
    # === BEZIEHUNG (merge all relationship variants) ===
    "Beziehungen": "Beziehung",
    "Beziehungstipps": "Beziehung",
    "Beziehungsratgeber": "Beziehung",
    "Beziehungsratschläge": "Beziehung",
    "Beziehungs-Tipps": "Beziehung",
    "Beziehungsprobleme": "Beziehung",
    "Beziehungs-Probleme": "Beziehung",
    "Beziehungsformen": "Beziehung",
    "Beziehungsmodelle": "Beziehung",
    "Beziehungstypen": "Beziehung",
    "Beziehungsstil": "Beziehung",
    "Beziehungskrise": "Beziehung",
    "Beziehungskrisen": "Beziehung",
    "Beziehungsende": "Trennung",
    "Beziehungsaufbau": "Beziehung",
    "Beziehungspsychologie": "Psychologie",
    "Beziehungskommunikation": "Kommunikation",
    "Beziehungskompatibilität": "Beziehung",
    "Beziehungsgesundheit": "Beziehung",
    "Beziehungsziele Paare": "Beziehung",
    "Beziehungszyklus": "Beziehung",
    "Beziehungsrituale": "Beziehung",
    "Beziehungsstress Reise": "Beziehung",
    "Beziehungsentscheidung": "Beziehung",
    "Beziehung Auffrischen": "Beziehung",
    "Beziehung Finden": "Partnersuche",
    "Beziehung Retten Betrug": "Vertrauen",
    "Beziehung Retten nach Betrug": "Vertrauen",
    "Beziehung nach Betrug": "Vertrauen",
    "Beziehung nach Untreue": "Vertrauen",
    "Beziehung nach Baby": "Familie",
    "Beziehung nach Fehlgeburt": "Familie",
    "Beziehung nach IVF": "Familie",
    "Beziehung nach Corona": "Beziehung",
    "Beziehung Burnout": "Beziehung",
    "Beziehung Heilen": "Beziehung",
    "Beziehung Spannend Halten": "Beziehung",
    "Beziehung Stärken": "Beziehung",
    "Beziehung Vertiefen": "Beziehung",
    "Beziehung Arbeit": "Beziehung",
    "Beziehung Streiten": "Konflikte",
    "Beziehung Haushalt": "Zusammenleben",
    "Beziehung Auswanderung": "Beziehung",
    "Beziehung Gaming": "Beziehung",
    "Beziehung Jahrestag": "Beziehung",
    "Beziehung Politik": "Beziehung",
    "Beziehung Trauerfall": "Beziehung",
    "Beziehung Verlust": "Beziehung",
    "Beziehung Zusammenziehen": "Zusammenleben",
    "Beziehung Später im Leben": "Beziehung",
    "Beziehung mit Kind": "Familie",
    "Beziehung mit Kindern": "Familie",
    "Beziehung unter der Woche Getrennt": "Fernbeziehung",
    "Beziehung Altersunterschied": "Beziehung",
    "Beziehung auf Augenhöhe": "Beziehung",
    "Beziehung Digital Detox": "Digital Detox",
    "Beziehung Dankbarkeit": "Beziehung",
    "Beziehung Date Night": "Date-Ideen",
    "Beziehung Eifersucht": "Eifersucht",
    "Beziehung Eigene Identität": "Selbstliebe",
    "Beziehung Emotionale Distanz": "Kommunikation",
    "Moderne Beziehungen": "Beziehung",
    "Langzeitbeziehung": "Beziehung",
    "Langzeitbeziehung Langeweile": "Beziehung",
    "Langzeit Paar Tipps": "Beziehung",
    "Lange Beziehung Geheimnis": "Beziehung",
    "Paarbeziehung": "Beziehung",
    "Erfolgreiche Beziehung": "Beziehung",
    "Gesunde Beziehung": "Beziehung",
    "Wie Beziehung Aufbauen": "Beziehung",
    "Digitale Beziehung": "Online-Dating",
    "Internationale Beziehung": "Fernbeziehung",
    "Relationships": "Beziehung",
    "Relationship Health Check": "Beziehung",
    "Partnerschaft": "Beziehung",
    "Partnerschaften Verbessern": "Beziehung",
    "Partnerschaftsformen": "Beziehung",
    "Paare": "Beziehung",
    "Paar-Planung": "Beziehung",
    "Paarcommunication": "Kommunikation",
    "Paarkommunikation": "Kommunikation",
    "Paarcoaching": "Paartherapie",
    "Paare Arbeiten Zusammen": "Beziehung",
    "Paare Rituale": "Beziehung",
    "Paar Bucket List": "Date-Ideen",
    "Paar Gemeinsam Abnehmen": "Gesundheit",
    "Paar Gemeinsam Wachsen": "Beziehung",
    "Paar Gewohnheiten": "Beziehung",
    "Daten Beziehung": "Beziehung",

    # === DATING (merge all dating variants) ===
    "Dating-Tipps": "Dating",
    "Tipps": "Dating",
    "Dating-Psychologie": "Psychologie",
    "Dating-Trends": "Dating",
    "Dating Trends": "Dating",
    "Dating-Trends 2026": "Dating",
    "Dating Trends 2026": "Dating",
    "Dating Veränderungen 2026": "Dating",
    "Trends": "Dating",
    "Dating-Probleme": "Dating",
    "Dating-Phasen": "Dating",
    "Dating-Begriffe": "Dating",
    "Dating-Rot-Flaggen": "Red Flags",
    "Dating-Sicherheit": "Sicherheit",
    "Dating Sicherheit": "Sicherheit",
    "Dating-Tipps Gesundheit": "Gesundheit",
    "Dating-nach-Trennung": "Neuanfang",
    "Dating-tipps für Eltern": "Familie",
    "Dating Mythen": "Dating",
    "Dating Fakten": "Dating",
    "Dating Regeln Brechen": "Dating",
    "Dating Statistiken 2026": "Dating",
    "Dating Wahrheit": "Dating",
    "Dating Strategie": "Dating",
    "Dating Verhalten Verbessern": "Dating",
    "Dating Gewohnheiten Ändern": "Dating",
    "Dating Persönlichkeitstypen": "Dating",
    "Dating Burnout": "Dating",
    "Dating Erschöpfung": "Dating",
    "Dating Müde": "Dating",
    "Dating Anstrengend": "Dating",
    "Dating Pause": "Dating",
    "Dating Stress Reduzieren": "Dating",
    "Dating Coach": "Dating",
    "Dating Coach Kosten": "Dating",
    "Dating Coaching Erfahrungen": "Dating",
    "Dating Betrug": "Sicherheit",
    "Dating Manipulation": "Red Flags",
    "Dating Selbstvertrauen": "Selbstliebe",
    "Moderne-Dating": "Dating",
    "Effizientes Dating": "Dating",
    "Ehrliches Dating": "Dating",
    "Ehrlichkeit Dating": "Dating",
    "Bewusstes Dating": "Dating",
    "Achtsames Daten": "Dating",
    "Authentisch Daten": "Dating",
    "Authentisch Dating": "Dating",
    "Authentisch Bleiben": "Dating",
    "Erwachsenen-Dating": "Dating",
    "Micro-Dating": "Dating",
    "Minimalistisch Daten": "Dating",
    "Welcher Dating Typ Bin Ich": "Dating",
    "Sicher Wieder Daten": "Neuanfang",
    "Wieder Datin nach Langer Beziehung": "Neuanfang",
    "Veraltete Dating Tipps": "Dating",
    "Endloses Swipen Aufhoeren": "Dating",
    "Weniger Dates Mehr Qualitaet": "Dating",
    "Schlechte Dating Muster": "Dating",
    "Wann Sollte Ich Aufgeben Dating": "Dating",
    "Wie Viel Zeit Dating": "Dating",
    "Datting Conversation Starters": "Flirten",
    "Conversation Starter": "Flirten",
    "Gesprächsstarter": "Flirten",

    # === ONLINE-DATING ===
    "Online Dating": "Online-Dating",
    "Online Date Tipps": "Online-Dating",
    "Online Dating Frauen": "Online-Dating",
    "Online Dating Kosten": "Online-Dating",
    "Online Dating Safety": "Sicherheit",
    "Online Dating Senioren": "Online-Dating",
    "Online Dating Statistiken": "Online-Dating",
    "Online Dating Tipps": "Online-Dating",
    "Online Dating Trends": "Online-Dating",
    "Online Dating Zeitmanagement": "Online-Dating",
    "Online Dating über 30": "Online-Dating",
    "Online-Dating-Trend": "Online-Dating",
    "Chat-Dating": "Online-Dating",
    "Chat-Tipps": "Online-Dating",
    "WhatsApp-Dating": "Online-Dating",
    "Video Dating": "Online-Dating",
    "Video Call Date": "Online-Dating",
    "Virtuelle Dates": "Online-Dating",
    "Digitale Liebe": "Online-Dating",
    "Digitale Etikette": "Online-Dating",
    "Digitales Leben": "Online-Dating",
    "Digital": "Online-Dating",

    # === DATING-APPS ===
    "Dating Apps": "Dating-Apps",
    "Apps": "Dating-Apps",
    "App-Test": "Dating-Apps",
    "Tinder": "Dating-Apps",
    "Tinder Kosten": "Dating-Apps",
    "Tinder Profil Optimieren": "Dating-Apps",
    "Tinder Sucht": "Dating-Apps",
    "Wie Tinder Funktioniert": "Dating-Apps",
    "Bumble": "Dating-Apps",
    "Bumble Kosten": "Dating-Apps",
    "Hinge": "Dating-Apps",
    "Kostenlose Dating Apps": "Dating-Apps",
    "Dating App Algorithmen": "Dating-Apps",
    "Dating App Effizienz": "Dating-Apps",
    "Dating App Matches": "Dating-Apps",
    "Dating App Nachricht": "Dating-Apps",
    "Dating App Preise 2026": "Dating-Apps",
    "Dating App Profil Tipps": "Dating-Apps",
    "Dating App Sucht": "Dating-Apps",
    "Beste Dating App": "Dating-Apps",
    "Matchmaking Algorithmen": "Dating-Apps",
    "Swipe Fatigue": "Dating-Apps",
    "Doomscrolling Dating App": "Dating-Apps",
    "Scoring": "Dating-Apps",
    "Test 2026": "Dating-Apps",
    "Vergleich": "Dating-Apps",
    "Vergleich 2026": "Dating-Apps",
    "Bewertung": "Dating-Apps",
    "Queer Dating Apps": "LGBTQ+",
    "Matches Erhöhen": "Dating-Apps",
    "Match Nachrichten": "Flirten",

    # === PROFIL-TIPPS -> merge into Dating-Apps ===
    "Profil-Tipps": "Dating-Apps",
    "Profiloptimierung": "Dating-Apps",
    "Profil": "Dating-Apps",
    "Dating-Profil": "Dating-Apps",
    "Dating Profil Bio": "Dating-Apps",
    "Dating Profil Frauen": "Dating-Apps",
    "Dating Profilbild": "Dating-Apps",
    "Gute Bio Texte": "Dating-Apps",
    "Profilfotos": "Dating-Apps",
    "Fotos": "Dating-Apps",
    "Beste Profilfotos": "Dating-Apps",

    # === FLIRTEN ===
    "Körpersprache": "Flirten",
    "Nonverbal Kommunikation": "Flirten",
    "Rizz": "Flirten",
    "Rizz Bedeutung": "Flirten",
    "Was Ist Rizz": "Flirten",
    "Opener": "Flirten",
    "Ansprechen": "Flirten",
    "Komplimente": "Flirten",
    "Messaging": "Flirten",
    "Texting": "Flirten",
    "Erste-Nachricht": "Flirten",
    "Erste Nachricht": "Flirten",
    "Erste Nachricht Dating-App": "Flirten",
    "Wie Man Nachrichten auf Dating-Apps": "Flirten",
    "Nachrichten": "Flirten",
    "Smalltalk Themen Dating": "Flirten",
    "Gesprächsthemen First Date": "Flirten",
    "Was Fragen Beim Date": "Flirten",
    "Fragen Stellen": "Flirten",
    "Kissing Escalation": "Flirten",
    "Küssen": "Flirten",
    "Gen Z Flirten": "Flirten",
    "Flirtcoaching": "Flirten",
    "Konversation": "Flirten",
    "Kommunikation Verbessern Dating": "Flirten",
    "Kommunikationsstile Dating": "Kommunikation",
    "Dirty Talk Lernen": "Intimität",
    "Dirty Talk Tipps": "Intimität",
    "Erotische Kommunikation": "Intimität",

    # === ERSTES DATE ===
    "Erste Dates": "Erstes Date",
    "Erstes-Date": "Erstes Date",
    "Erstes-Treffen": "Erstes Date",
    "Erstes Treffen": "Erstes Date",
    "Erste Date Tipps": "Erstes Date",
    "Erste Schritte Dating": "Erstes Date",
    "Nervosität Beim Ersten Treffen": "Erstes Date",
    "Nervös Beim Date": "Erstes Date",
    "Nervosität": "Erstes Date",
    "Zweites Date": "Erstes Date",
    "Date-Outfit": "Erstes Date",
    "Styling": "Erstes Date",
    "Vorbereitung": "Erstes Date",

    # === DATE-IDEEN ===
    "Date Ideen": "Date-Ideen",
    "Kreative Dates": "Date-Ideen",
    "Aktivitäten": "Date-Ideen",
    "Aktivitäten Paare": "Date-Ideen",
    "Hobbys": "Date-Ideen",
    "Abenteuer": "Date-Ideen",
    "Gratis Dates": "Date-Ideen",
    "Günstige Dates": "Date-Ideen",
    "Luxus Dates": "Date-Ideen",
    "Outdoor Dating": "Date-Ideen",
    "Outdoor-Aktivitäten": "Date-Ideen",
    "Saisonale Dates": "Date-Ideen",
    "Saisonales Dating": "Date-Ideen",
    "Sommer-Dating": "Date-Ideen",
    "Frühling": "Date-Ideen",
    "Frühlings Date Ideen": "Date-Ideen",
    "Jahreszeiten": "Date-Ideen",
    "Quality Time": "Date-Ideen",
    "Quality Time Weekend": "Date-Ideen",
    "Quality Time ohne Handy": "Date-Ideen",
    "Date Night": "Date-Ideen",
    "Date Night Ideen Paare": "Date-Ideen",
    "Date Night Planen": "Date-Ideen",
    "Spontane-Dates": "Date-Ideen",
    "Kurze Dates": "Date-Ideen",
    "After Work Date": "Date-Ideen",
    "Dating After Work": "Date-Ideen",
    "Erlebnisse Zusammen": "Date-Ideen",
    "Spaß": "Date-Ideen",
    "Speed-Dating": "Date-Ideen",
    "Dry Dating": "Date-Ideen",
    "Analog Dating": "Date-Ideen",
    "Dating Offline": "Date-Ideen",
    "Offline-Dating": "Date-Ideen",
    "Offline": "Date-Ideen",
    "Wochenend Ideen Beziehung": "Date-Ideen",
    "Weekend Rituale": "Date-Ideen",
    "Weekend Rituals Paare": "Date-Ideen",
    "Wochenend Routine Paare": "Date-Ideen",
    "Restaurants": "Date-Ideen",

    # === SELBSTLIEBE (merge self-related) ===
    "Selbstbewusstsein": "Selbstliebe",
    "Selbstvertrauen": "Selbstliebe",
    "Selbstwert": "Selbstliebe",
    "Selbstwertgefühl": "Selbstliebe",
    "Selbstentwicklung": "Selbstliebe",
    "Persönlichkeitsentwicklung": "Selbstliebe",
    "Persoenlichkeitsentwicklung": "Selbstliebe",
    "Persönliche Entwicklung": "Selbstliebe",
    "Selbstkenntnis": "Selbstliebe",
    "Selbsterkenntnis": "Selbstliebe",
    "Selbstverständnis": "Selbstliebe",
    "Selbstfürsorge": "Selbstliebe",
    "Selbstpflege": "Selbstliebe",
    "Selbstreflexion": "Selbstliebe",
    "Selbstheilung": "Selbstliebe",
    "Selbsthilfe": "Selbstliebe",
    "Selbstliebe nach Veränderung": "Selbstliebe",
    "Selbstbewusst Dating": "Selbstliebe",
    "Selbstbewusstsein Dating": "Selbstliebe",
    "Selbstvertrauen Behinderung": "Selbstliebe",
    "Wachstum": "Selbstliebe",
    "Mindset": "Selbstliebe",
    "Authentizität": "Selbstliebe",
    "Identität": "Selbstliebe",
    "Mut": "Selbstliebe",
    "Entwicklung": "Selbstliebe",
    "Entwicklung Zusammen": "Selbstliebe",
    "Transformation": "Selbstliebe",
    "Körperakzeptanz": "Selbstliebe",
    "Körperbild": "Selbstliebe",
    "Körperbild Dating": "Selbstliebe",
    "Body Positivity Dating": "Selbstliebe",
    "Body Dysmorphia": "Selbstliebe",
    "Body Image Issues": "Selbstliebe",
    "Gewichtsveränderung Dating": "Selbstliebe",
    "Wahre Selbst Dating": "Selbstliebe",

    # === PSYCHOLOGIE ===
    "Emotionale Intelligenz": "Psychologie",
    "Emotional Intelligence": "Psychologie",
    "EQ Beziehung": "Psychologie",
    "Eq": "Psychologie",
    "Emotional": "Psychologie",
    "Anziehung": "Psychologie",
    "Dopamine": "Psychologie",
    "Neurochemie": "Psychologie",
    "Neurowissenschaft": "Psychologie",
    "Biologie": "Psychologie",
    "Wissenschaft": "Psychologie",
    "Seelenverwandtschaft": "Psychologie",
    "Liebessprachen": "Psychologie",
    "Persönlichkeit": "Psychologie",
    "Persönlichkeitstypen": "Psychologie",
    "Persönlichkeit Beziehung": "Psychologie",
    "Persönlichkeitsverschiedenheiten": "Psychologie",
    "Compatibility Types": "Psychologie",
    "Kompatibilität": "Psychologie",

    # === KOMMUNIKATION ===
    "Offene Kommunikation": "Kommunikation",
    "Fair Streiten": "Konflikte",
    "Gespräche": "Kommunikation",
    "Gefühle Zeigen": "Kommunikation",
    "Gefühle": "Kommunikation",
    "Sprache": "Kommunikation",

    # === KONFLIKTE ===
    "Konflikt": "Konflikte",
    "Konfliktlösung": "Konflikte",
    "Konfliktmanagement": "Konflikte",
    "Konfliktvermeidung": "Konflikte",
    "Konflikt Lösen": "Konflikte",
    "Konflikt Lösung": "Konflikte",
    "Konflikte Lösen": "Konflikte",
    "Konflikte Lösen Methode": "Konflikte",
    "Konfliktlösung Strategien": "Konflikte",
    "Wie Konflikte Lösen Paar": "Konflikte",
    "Gesunde Konflikte": "Konflikte",
    "Streit": "Konflikte",
    "Streitkultur": "Konflikte",
    "Aneinander Vorbeireden Beziehung": "Konflikte",
    "Werte Konflikt": "Konflikte",
    "Unterschiede": "Konflikte",

    # === VERTRAUEN ===
    "Vertrauen Aufbauen": "Vertrauen",
    "Vertrauen Wieder Aufbauen": "Vertrauen",
    "Vertrauensaufbau nach Betrug": "Vertrauen",
    "Vertrauensbruch Heilen": "Vertrauen",
    "Treue": "Vertrauen",
    "Untreue": "Vertrauen",
    "Untreue Verzeihen": "Vertrauen",
    "Fremdgehen": "Vertrauen",
    "Fremdgehen Verzeihen": "Vertrauen",
    "Affäre": "Vertrauen",
    "Affäre Beziehung": "Vertrauen",
    "Affäre Überwinden": "Vertrauen",
    "Betrug": "Vertrauen",
    "Betrug Beziehung": "Vertrauen",
    "Betrug Beim Dating": "Sicherheit",
    "Lügen": "Vertrauen",
    "Lügen Beziehung": "Vertrauen",
    "Exklusivität Lügen": "Vertrauen",
    "Vergebung": "Vertrauen",
    "Versöhnung": "Vertrauen",
    "Zweite Chance": "Vertrauen",

    # === RED FLAGS (toxic behavior) ===
    "Red-Flags": "Red Flags",
    "Rote Flaggen": "Red Flags",
    "Rote Flaggen Dating": "Red Flags",
    "Red Flags Erkennen": "Red Flags",
    "Warnsignale": "Red Flags",
    "Warnzeichen Partner": "Red Flags",
    "Toxische Beziehung": "Red Flags",
    "Toxische Beziehungen": "Red Flags",
    "Toxische Beziehung Erkennen": "Red Flags",
    "Toxische Muster": "Red Flags",
    "Toxisches Verhalten": "Red Flags",
    "Manipulation": "Red Flags",
    "Manipulationen": "Red Flags",
    "Emotionale Manipulation": "Red Flags",
    "Narzissmus": "Red Flags",
    "Narzisstische Beziehung": "Red Flags",
    "Gaslighting Beispiele": "Red Flags",
    "Gaslighting Erkennen": "Red Flags",
    "Gaslighting Partnerschaft": "Red Flags",
    "Ghosting": "Red Flags",
    "Benching Dating": "Red Flags",
    "Breadcrumbing": "Red Flags",
    "Cushioning Dating": "Red Flags",
    "Roaching Dating": "Red Flags",
    "Orbiting Dating": "Red Flags",
    "Ex Orbiting": "Red Flags",
    "Catfishing": "Sicherheit",
    "Psychische Gewalt": "Red Flags",
    "Emotionaler Missbrauch": "Red Flags",
    "Missbrauch": "Red Flags",
    "Kontrolle": "Red Flags",
    "Hingehalten Werden": "Red Flags",
    "Hinhaltend Daten": "Red Flags",
    "Auf Wartebank": "Red Flags",
    "Fake Vs Authentic": "Red Flags",
    "Toxische Schwiegereltern": "Familie",

    # === TRENNUNG & NEUANFANG ===
    "Neustart": "Neuanfang",
    "Neubeginn": "Neuanfang",
    "Neue Anfänge": "Neuanfang",
    "Trennungsgründe": "Trennung",
    "Trennung Verarbeiten": "Trennung",
    "Trennung Ueberstehen": "Trennung",
    "Trennung Work Life Balance": "Trennung",
    "Faire Trennung": "Trennung",
    "Respektvolle Trennung": "Trennung",
    "Rosenkrieg Vermeiden": "Trennung",
    "Scheidung": "Trennung",
    "Scheidungsquote Deutschland": "Trennung",
    "Erste Tage nach Trennung": "Neuanfang",
    "Nach Langzeitbeziehung": "Neuanfang",
    "Plötzlich Single": "Neuanfang",
    "Von Single zu Beziehung": "Neuanfang",
    "Dating nach Beziehung": "Neuanfang",
    "Nach Langer Single-Zeit Beziehung": "Neuanfang",
    "Lange Single Gewesen": "Neuanfang",
    "Spätstart Beziehung": "Neuanfang",
    "Trauer Neuanfang": "Neuanfang",

    # === LIEBESKUMMER ===
    "Unglücklich Verliebt": "Liebeskummer",
    "Verliebtheit": "Liebeskummer",
    "Verlustangst": "Liebeskummer",
    "Liebeskummer": "Liebeskummer",
    "Ex-Partner": "Liebeskummer",
    "Ex Zurückgewinnen": "Liebeskummer",
    "Ex Partnerin Eifersucht": "Eifersucht",

    # === EIFERSUCHT ===
    "Eifersucht auf Ex": "Eifersucht",
    "Eifersucht Überwinden": "Eifersucht",
    "Retroaktive Eifersucht": "Eifersucht",
    "Rebecca Syndrom": "Eifersucht",

    # === FERNBEZIEHUNG ===
    "Long-Distance": "Fernbeziehung",
    "Long Distance": "Fernbeziehung",
    "Long Distance Relationship": "Fernbeziehung",
    "Langdistanzbeziehung": "Fernbeziehung",
    "Fernbeziehung Ausland": "Fernbeziehung",
    "Fernbeziehung Tipps": "Fernbeziehung",
    "Pendler-Beziehung": "Fernbeziehung",
    "Wochenend-Beziehung": "Fernbeziehung",
    "LAT Beziehung": "Fernbeziehung",
    "Living Apart Together": "Fernbeziehung",
    "Getrennte Wohnungen": "Fernbeziehung",
    "Liebe auf Distanz": "Fernbeziehung",
    "Liebe Neues Land": "Fernbeziehung",

    # === FAMILIE ===
    "Alleinerziehend": "Familie",
    "Single-Parent": "Familie",
    "Single Parent Dating": "Familie",
    "Single Mama Dating": "Familie",
    "Dating Alleinerziehend": "Familie",
    "Dating mit Kind": "Familie",
    "Dating mit Kindern": "Familie",
    "Neue Beziehung mit Kindern": "Familie",
    "Kinder": "Familie",
    "Kinderwunsch": "Familie",
    "Unterschiedlicher Kinderwunsch": "Familie",
    "Elternschaft": "Familie",
    "Elternschaft Tipps": "Familie",
    "Erste Elternschaft": "Familie",
    "Erziehung Als Paar": "Familie",
    "Unterschiedliche Elternmethoden": "Familie",
    "Konsistenz in der Erziehung": "Familie",
    "Baby und Beziehung": "Familie",
    "Beziehungskrise nach Baby": "Familie",
    "Intimität mit Baby": "Familie",
    "Elternzeit Herausforderung": "Familie",
    "Patchwork": "Familie",
    "Co-Parenting": "Familie",
    "Schwiegereltern": "Familie",
    "Schwiegermutter": "Familie",
    "Familienbeziehung": "Familie",
    "Familienkonflikt": "Familie",
    "Fehlgeburt": "Familie",
    "Fehlgeburt Trauer": "Familie",
    "Verlust Baby Partnerschaft": "Familie",
    "IVF Beziehung": "Familie",
    "Fertilitätsbehandlung Stress": "Familie",
    "Paartherapie Fertilität": "Familie",
    "Schwanger Partnersuche": "Familie",
    "Partnersuche Schwangerschaft": "Familie",
    "Dating Schwanger": "Familie",
    "Ein Will Kinder": "Familie",
    "Mutter": "Familie",
    "Geburt": "Familie",

    # === ZUSAMMENLEBEN ===
    "Zusammenziehen": "Zusammenleben",
    "Zusammenziehen Checkliste": "Zusammenleben",
    "Zusammenziehen Planung": "Zusammenleben",
    "Zusammenleben Voraussetzungen": "Zusammenleben",
    "Zusammenleben Lockdown": "Zusammenleben",
    "Erste Gemeinsame Wohnung": "Zusammenleben",
    "Haushalt": "Zusammenleben",
    "Haushalt Fair Aufteilen": "Zusammenleben",
    "Haushaltsaufgaben Paar": "Zusammenleben",
    "Putzplan Partner": "Zusammenleben",
    "Gemeinsame Kasse": "Zusammenleben",
    "Getrennt Schlafen Beziehung": "Zusammenleben",
    "Getrennte Betten Paar": "Zusammenleben",
    "Verschiedene Schlafgewohnheiten": "Zusammenleben",
    "Schlafmuster Partnerschaft": "Zusammenleben",
    "Unterschiedliche Schlafzeiten Paar": "Zusammenleben",
    "Eule und Lerche Beziehung": "Zusammenleben",
    "Schlaf und Partnerschaft": "Zusammenleben",
    "Routinen": "Zusammenleben",
    "Couple Routines": "Zusammenleben",
    "Alltag": "Zusammenleben",
    "Alltagstipps": "Zusammenleben",
    "Gewohnheiten": "Zusammenleben",
    "Rituale": "Zusammenleben",
    "Meilensteine": "Zusammenleben",
    "Umzug": "Zusammenleben",
    "Gemeinsames Haustier": "Zusammenleben",
    "Haustiere": "Zusammenleben",
    "Hund Katze Beziehung": "Zusammenleben",
    "Haustier Paar": "Zusammenleben",

    # === HOCHZEIT ===
    "Hochzeit": "Hochzeit",
    "Hochzeitsplanung": "Hochzeit",
    "Hochzeitsplanung Stressfrei": "Hochzeit",
    "Hochzeitsplanung Tipps": "Hochzeit",
    "Hochzeit Budget": "Hochzeit",
    "Hochzeit Kosten 2026": "Hochzeit",
    "Hochzeit Planen": "Hochzeit",
    "Hochzeit Statistik Deutschland": "Hochzeit",
    "Hochzeit Trends": "Hochzeit",
    "Heiratsantrag": "Hochzeit",
    "Verlobung": "Hochzeit",
    "Verlobung Bedeutung": "Hochzeit",
    "Verlobung Tradition": "Hochzeit",
    "Verlobungsring": "Hochzeit",
    "Ehe": "Hochzeit",
    "Ehe Tipps": "Hochzeit",
    "Ehejahre": "Hochzeit",
    "Jahrestag": "Hochzeit",
    "Jahrestag Feiern": "Hochzeit",
    "Jahrestag Ideen": "Hochzeit",
    "10 Jahre Zusammen": "Hochzeit",

    # === GESUNDHEIT (mental + physical) ===
    "Mental Health": "Gesundheit",
    "Mentale Gesundheit": "Gesundheit",
    "Psychische Gesundheit": "Gesundheit",
    "Emotionale Gesundheit": "Gesundheit",
    "Emotionale-Gesundheit": "Gesundheit",
    "Psychische Belastung Partnerschaft": "Gesundheit",
    "Wellness": "Gesundheit",
    "Wellbeing": "Gesundheit",
    "Burnout": "Gesundheit",
    "Burnout Partner Unterstützen": "Gesundheit",
    "Depression": "Gesundheit",
    "Depression Beziehung": "Gesundheit",
    "Partner mit Depression": "Gesundheit",
    "Angst": "Gesundheit",
    "Angststörung Dating": "Gesundheit",
    "Soziale Angst": "Gesundheit",
    "Soziale Phobie": "Gesundheit",
    "Panikattacken": "Gesundheit",
    "Stress": "Gesundheit",
    "Stress-Management": "Gesundheit",
    "Stressbewältigung": "Gesundheit",
    "Stress durch Karriere": "Gesundheit",
    "Schlaf": "Gesundheit",
    "Müdigkeit": "Gesundheit",
    "Erschöpfung": "Gesundheit",
    "Sucht": "Gesundheit",
    "Alkoholfrei": "Gesundheit",
    "Alkoholfreies Dating": "Gesundheit",
    "Nüchternes Daten": "Gesundheit",
    "Meditation": "Gesundheit",
    "Achtsamkeit": "Gesundheit",
    "Gesundheitskrise Beziehung": "Gesundheit",
    "Gesundheitsziele Beziehung": "Gesundheit",
    "Chronische Krankheit": "Gesundheit",
    "Krankheit": "Gesundheit",
    "Dating mit Krankheit": "Gesundheit",
    "Dating mit Einschränkungen": "Gesundheit",
    "Fibromyalgie": "Gesundheit",
    "Krebs Beziehung": "Gesundheit",
    "Partner Krebs Diagnose": "Gesundheit",
    "Zusammenhalt Krankheit": "Gesundheit",
    "Diät Als Paar": "Gesundheit",
    "Gegenseitige Unterstützung Gewicht": "Gesundheit",
    "Verschiedene Essgewohnheiten": "Gesundheit",
    "Ernährungs-Konflikte": "Gesundheit",
    "Vegan": "Gesundheit",
    "Veganismus": "Gesundheit",
    "Vegetarianismus": "Gesundheit",
    "Vegan Fleischesser Beziehung": "Gesundheit",
    "Lebensmittelunverträglichkeiten Dating": "Gesundheit",
    "Restaurant Allergie Management": "Gesundheit",
    "Dating Allergien": "Gesundheit",
    "Frauengesundheit": "Gesundheit",
    "Libido": "Intimität",
    "Dating nach Essstörung": "Gesundheit",
    "Dating nach Schönheits-OP": "Gesundheit",
    "Plastische Chirurgie Dating": "Gesundheit",
    "Neue Aussehen Dating": "Gesundheit",
    "Recovery Dating": "Gesundheit",
    "Körper-Veränderungen Beziehung": "Gesundheit",
    "Dating Übergewicht": "Gesundheit",

    # === TRAUMA & HEILUNG ===
    "Trauma": "Heilung",
    "Heilung": "Heilung",
    "Trauma Healing Dating": "Heilung",
    "Trauma-recovery": "Heilung",
    "Traumaheilung": "Heilung",
    "Trauma nach Katastrophe": "Heilung",
    "Religiöses Trauma": "Heilung",
    "Dating nach Missbrauch": "Heilung",
    "Dating nach Religiöser Enttäuschung": "Heilung",
    "Trauer": "Heilung",
    "Trauer in Beziehung": "Heilung",
    "Trauer Partner Unterstützen": "Heilung",
    "Gemeinsam Trauern": "Heilung",
    "Dating nach Trauer": "Heilung",
    "Neuer Partner nach Tod": "Heilung",
    "Verwitwet Dating": "Heilung",
    "Naturkatastrophe Beziehung": "Heilung",
    "Verlust": "Heilung",
    "Lebenskrise": "Heilung",
    "Krisen Bewältigung Paar": "Heilung",
    "Krise": "Heilung",

    # === INTIMITÄT ===
    "Sexualität": "Intimität",
    "Sexuelle Orientierung": "Intimität",
    "Sexuelle Wünsche": "Intimität",
    "Über Sex Reden": "Intimität",
    "Nähe": "Intimität",
    "Emotionale Nähe": "Intimität",
    "Körperliche Nähe": "Intimität",
    "Körperliche Nähe Aufbauen Dating": "Intimität",
    "Körperliche Nähe Beziehung": "Intimität",
    "Intimität Verbessern": "Intimität",
    "Intimität Zurück": "Intimität",
    "Leidenschaft": "Intimität",
    "Leidenschaft Beziehung": "Intimität",
    "Leidenschaft Zurückholen": "Intimität",
    "Romantik": "Intimität",
    "Romantische Überraschungen": "Intimität",
    "Romantische Briefe": "Intimität",
    "Romantische Asexualität": "Intimität",
    "Liebesbeweis Alltag": "Intimität",
    "Liebesbrief Schreiben": "Intimität",
    "Liebesbriefe Vorlagen": "Intimität",
    "Liebeserklärung Brief": "Intimität",
    "Briefe": "Intimität",
    "Kuscheln Bedeutung": "Intimität",
    "Kuschelpartner": "Intimität",
    "Oxytocin Kuscheln": "Intimität",
    "Erste Körperliche Kontakte": "Intimität",
    "Kleine Gesten Liebe": "Intimität",
    "Verbindung": "Intimität",
    "Emotionale Verbindung": "Intimität",
    "Emotionale Bindung": "Intimität",
    "Schmetterlinge Zurück": "Intimität",
    "Nähe ohne Handy": "Intimität",
    "Partner Überraschen": "Intimität",

    # === FINANZEN ===
    "Finanzen": "Finanzen",
    "Geld": "Finanzen",
    "Geld in Beziehung": "Finanzen",
    "Geld in Partnerschaft": "Finanzen",
    "Gemeinsame Finanzen": "Finanzen",
    "Geldmanagement": "Finanzen",
    "Budget": "Finanzen",
    "Finanzielle Harmonie": "Finanzen",
    "Finanzielle Planung Paare": "Finanzen",
    "Finanzielle Sicherheit": "Finanzen",
    "Finanzielle Stress": "Finanzen",
    "Finanzplanung Paare": "Finanzen",
    "Ungleichgewicht": "Finanzen",

    # === BINDUNGSTYPEN ===
    "Attachment Styles": "Bindungstypen",
    "Bindungsstil": "Bindungstypen",
    "Bindungstheorie": "Bindungstypen",
    "Bindungsangst": "Bindungstypen",
    "Bindung": "Bindungstypen",

    # === LGBTQ+ ===
    "LGBTQ": "LGBTQ+",
    "LGBTQ+ Dating": "LGBTQ+",
    "Queer Partnersuche": "LGBTQ+",
    "Queeres Dating": "LGBTQ+",
    "Lgbtq Dating": "LGBTQ+",
    "Coming Out": "LGBTQ+",
    "Lesbian Dating": "LGBTQ+",
    "Schwules Dating": "LGBTQ+",
    "Bi Dating": "LGBTQ+",

    # === NEURODIVERSITÄT ===
    "Neurodiversität": "Neurodiversität",
    "Hochsensibilität": "Neurodiversität",
    "HSP": "Neurodiversität",
    "HSP Dating": "Neurodiversität",
    "Hochsensible Person": "Neurodiversität",
    "Hochsensible Frau Dating": "Neurodiversität",
    "Sensible Frauen Beziehung": "Neurodiversität",
    "Introversion": "Neurodiversität",
    "Introvertiert": "Neurodiversität",
    "Introvertiert Daten": "Neurodiversität",
    "Introvertiert Extrovertiert Paar": "Neurodiversität",
    "Dating für Introvertierte": "Neurodiversität",
    "ADHS": "Neurodiversität",
    "Autismus": "Neurodiversität",
    "Autistische Beziehungen": "Neurodiversität",
    "Dating Autismus": "Neurodiversität",
    "Neurodivergent Daten": "Neurodiversität",
    "Hochbegabung": "Neurodiversität",
    "Hochbegabt Partnersuche": "Neurodiversität",
    "Dating Hochbegabung": "Neurodiversität",
    "Intelligente Singles Dating": "Neurodiversität",
    "Intelligenz": "Neurodiversität",
    "Intelligenz und Liebe": "Neurodiversität",
    "Demisexuell": "Neurodiversität",
    "Asexualität Dating": "Neurodiversität",
    "Asexuell Spektrum": "Neurodiversität",
    "Asexuell-spektrum": "Neurodiversität",
    "Asexuelle Beziehung": "Neurodiversität",
    "Ace Dating": "Neurodiversität",
    "Aromantisch": "Neurodiversität",
    "Schüchternheit": "Neurodiversität",
    "Schüchternheit Überwinden": "Neurodiversität",
    "Dating Schüchtern": "Neurodiversität",
    "Dating Sensibilität": "Neurodiversität",

    # === DIGITAL DETOX ===
    "Digital Detox": "Digital Detox",
    "Digital Detox Paar": "Digital Detox",
    "Digitales Detox": "Digital Detox",
    "Digitales Ablenkung Liebe": "Digital Detox",
    "Handy Freie Zeit": "Digital Detox",
    "Handy Zerstört Beziehung": "Digital Detox",
    "Phubbing Beziehung": "Digital Detox",
    "Smartphones Beziehung": "Digital Detox",
    "Screen Time": "Digital Detox",
    "Zu Viel Handy Zeit": "Digital Detox",
    "Bildschirm Pause": "Digital Detox",
    "Social Media Addiction": "Digital Detox",
    "Social Media Stalking": "Digital Detox",
    "Technologie": "Digital Detox",

    # === SICHERHEIT ===
    "Schutz": "Sicherheit",
    "Selbstschutz": "Sicherheit",
    "Online Dating Safety": "Sicherheit",

    # === PARTNERSUCHE ===
    "Partnersuche 30er": "Partnersuche",
    "Partnersuche Grossstadt": "Partnersuche",
    "Partnersuche nach Abschluss": "Partnersuche",
    "Perfekten Partner Finden": "Partnersuche",
    "Gute Qualitäten Partner": "Partnersuche",
    "Dealbreaker": "Partnersuche",
    "Was Ist Dealbreaker": "Partnersuche",
    "Deal Breaker Männer Vs Frauen": "Partnersuche",
    "Hohe Ansprüche Dating": "Partnersuche",
    "Zu Hohe Ansprüche Dating": "Partnersuche",
    "Perfektionismus Dating": "Partnersuche",

    # === KENNENLERNEN ===
    "Kennenlernen": "Kennenlernen",

    # === LOKALES DATING ===
    "Lokales Dating": "Lokales Dating",
    "Dating Dresden": "Lokales Dating",
    "Dating Düsseldorf": "Lokales Dating",
    "Dating Hannover": "Lokales Dating",
    "Dating Leipzig": "Lokales Dating",
    "Dating Stuttgart": "Lokales Dating",
    "Baden-Württemberg": "Lokales Dating",
    "Sachsen": "Lokales Dating",
    "Stadt": "Lokales Dating",
    "Deutschland": "Lokales Dating",
    "Dating auf dem Land": "Lokales Dating",
    "Dating Stadt Land Unterschied": "Lokales Dating",

    # === LEBENSPHASEN ===
    "Dating Ab 40": "Lebensphasen",
    "Dating über 40": "Lebensphasen",
    "Ü40": "Lebensphasen",
    "Ü30": "Lebensphasen",
    "Über50": "Lebensphasen",
    "Single über 40": "Lebensphasen",
    "Dating Ab 60": "Lebensphasen",
    "Dating nach 60": "Lebensphasen",
    "Senior Dating Tipps": "Lebensphasen",
    "Dating Ab 30": "Lebensphasen",
    "Dating mit 30": "Lebensphasen",
    "Dating über 30": "Lebensphasen",
    "Dating nach Studium": "Lebensphasen",
    "Nach Uni Daten": "Lebensphasen",
    "Zu Alt Zum Dating Anfangen": "Lebensphasen",
    "Lebensphase": "Lebensphasen",
    "Lebensübergang": "Lebensphasen",
    "Lebensveränderung": "Lebensphasen",
    "Altern": "Lebensphasen",
    "Gen Z Dating": "Lebensphasen",
    "Millennials Dating": "Lebensphasen",
    "Generationenunterschiede Beziehung": "Lebensphasen",
    "Studium": "Lebensphasen",
    "Phasen": "Lebensphasen",
    "Phasen Beziehung": "Lebensphasen",
    "Phases": "Lebensphasen",
    "Honeymoon Phase": "Lebensphasen",
    "Erste Jahre": "Lebensphasen",
    "Gewöhnung an Partnerschaft": "Lebensphasen",
    "Berufstätige Daten": "Lebensphasen",

    # === LIFESTYLE ===
    "Lifestyle": "Lifestyle",
    "Kultur": "Lifestyle",
    "Interkulturell": "Lifestyle",
    "Gesellschaft": "Lifestyle",
    "Gesellschaftlicher Druck": "Lifestyle",
    "Lifestyle Unterschiede": "Lifestyle",
    "Karriere": "Lifestyle",
    "Beruf": "Lifestyle",
    "Work-Life-Balance": "Lifestyle",
    "Workaholic": "Lifestyle",
    "Produktivität": "Lifestyle",
    "Karriereumbruch Beziehung": "Lifestyle",
    "Partner Jobwechsel Unterstützen": "Lifestyle",
    "Arbeitslosigkeit": "Lifestyle",
    "Gemeinsames Business Beziehung": "Lifestyle",
    "Business Partner und Liebhaber": "Lifestyle",
    "Kreativität": "Lifestyle",
    "Kreatives Schreiben": "Lifestyle",
    "Bücher": "Lifestyle",
    "Fotografie": "Lifestyle",
    "Design": "Lifestyle",
    "Nerd-Kultur": "Lifestyle",
    "Astrologie": "Lifestyle",
    "Sternzeichen": "Lifestyle",
    "Spiritualität": "Lifestyle",
    "Spiritualität bei der Partnersuche": "Lifestyle",
    "Glaube und Liebe": "Lifestyle",
    "Humor": "Lifestyle",
    "Verschiedene Ueberzeugungen Paar": "Lifestyle",
    "Verschiedene Politische Ansichten": "Lifestyle",
    "Politische Meinungen Partnerschaft": "Lifestyle",
    "Politische Unterschiede Beziehung": "Lifestyle",
    "Politik": "Lifestyle",
    "Musikgeschmack Beziehung": "Lifestyle",
    "Musikgeschmack Kompatibel": "Lifestyle",
    "Verschiedene Musik Paar": "Lifestyle",
    "Gleichberechtigung": "Lifestyle",
    "Fairness": "Lifestyle",
    "Gerechtigkeitsempfinden": "Lifestyle",
    "Werte": "Lifestyle",
    "Lebensstil": "Lifestyle",
    "Freizeit": "Lifestyle",
    "Unterhaltung": "Lifestyle",
    "Reisen Als Paar": "Lifestyle",
    "Erste Gemeinsame Reise": "Lifestyle",
    "Urlaub": "Lifestyle",
    "Urlaubsplanung": "Lifestyle",
    "Getrennte Urlaube": "Lifestyle",
    "Solo Reisen Partner": "Lifestyle",
    "Auswanderung": "Lifestyle",
    "Expat": "Lifestyle",
    "Migration": "Lifestyle",
    "Militär": "Lifestyle",

    # === PAARTHERAPIE ===
    "Paartherapie Erfolg": "Paartherapie",
    "Paartherapie Techniken": "Paartherapie",
    "Nach Paartherapie": "Paartherapie",
    "Therapie": "Paartherapie",

    # === MISC mappings for remaining tags ===
    "Ratgeber": "Ratgeber",
    "Liebe": "Beziehung",
    "Grenzen": "Grenzen",
    "Grenzen setzen": "Grenzen",
    "Single": "Single-Leben",
    "Single-Leben": "Single-Leben",
    "Einsamkeit": "Single-Leben",
    "Casual-Dating": "Single-Leben",
    "Situationship": "Single-Leben",
    "Situationship Definition": "Single-Leben",
    "Was Ist Situationship": "Single-Leben",
    "Freundschaft Plus": "Single-Leben",
    "Undefined Beziehung": "Single-Leben",
    "DTR": "Single-Leben",
    "Social Media": "Digital Detox",
    "Social Media und Liebe": "Digital Detox",
    "Echte Beziehung Vs Social Media": "Digital Detox",
    "Instagram Beziehungen": "Digital Detox",
    "Soziale Netzwerke": "Digital Detox",
    "KI-Dating": "Online-Dating",
    "KI": "Online-Dating",
    "Slow Dating": "Dating",
    "Slow-Dating": "Dating",
    "Frauen": "Partnersuche",
    "Frauen Verstehen": "Partnersuche",
    "Männer": "Partnersuche",
    "Männer Verstehen": "Partnersuche",
    "Männerpsychologie": "Psychologie",
    "Behinderung": "Gesundheit",
    "Unsichtbare Behinderung": "Gesundheit",
    "Dating mit Behinderung": "Gesundheit",
    "Inklusion": "Gesundheit",
    "Inklusives Dating": "Gesundheit",
    "Pflege": "Gesundheit",
    "Geheimnis": "Beziehung",
    "Stärke": "Selbstliebe",
    "Persönlich": "Lifestyle",
    "Lebensplanung": "Lifestyle",
    "Zukunft": "Lifestyle",
    "Zukunftsplanung": "Lifestyle",
    "Gemeinsame Zukunft Planen": "Lifestyle",
    "Planung": "Lifestyle",
    "Roadmap": "Lifestyle",
    "Glück": "Selbstliebe",
    "Dankbarkeit": "Selbstliebe",
    "Akzeptanz": "Selbstliebe",
    "Geduld": "Selbstliebe",
    "Flexibilität": "Selbstliebe",
    "Balance": "Selbstliebe",
    "Resilienz": "Selbstliebe",
    "Resilience": "Selbstliebe",
    "Unabhängigkeit": "Selbstliebe",
    "Unabhängigkeit in Beziehung": "Selbstliebe",
    "Verantwortung": "Beziehung",
    "Respekt": "Beziehung",
    "Verständnis": "Kommunikation",
    "Kompromisse": "Konflikte",
    "Ehrlichkeit": "Vertrauen",
    "Klarheit": "Kommunikation",
    "Engagement": "Beziehung",
    "Entscheidung": "Beziehung",
    "Erinnerungen": "Beziehung",
    "Zusammenhalt": "Beziehung",
    "Wertschätzung": "Kommunikation",
    "Langeweile": "Date-Ideen",
    "Routine Durchbrechen": "Date-Ideen",
    "Zeit Zusammen": "Date-Ideen",
    "Zeit-Management": "Lifestyle",
    "Herausforderungen": "Beziehung",
    "Fehler": "Dating",
    "Anfänger": "Dating",
    "Dating ohne Erfahrung": "Dating",
    "Dating ohne Apps": "Date-Ideen",
    "Nachricht": "Flirten",
    "Freunde": "Kennenlernen",
    "Freundschaft": "Kennenlernen",
    "Erfolg": "Selbstliebe",
    "Statistik": "Dating",
    "Statistiken": "Dating",
    "Recht": "Trennung",
    "Unterstützung": "Beziehung",
    "Partner Unterstützung": "Beziehung",
    "Bewusst": "Dating",
    "Morgen": "Zusammenleben",
    "Pandemie Auswirkungen": "Dating",
    "Post-Covid Dating": "Dating",
    "Dating nach Pandemie": "Dating",
    "Green Flags": "Partnersuche",
    "Green Flags Dating": "Partnersuche",
    "Positive Zeichen Partner": "Partnersuche",
    "Bildung": "Lifestyle",
    "Strategie": "Dating",
    "Mental Load Dating": "Gesundheit",
    "Nicht-konventionelle Liebe": "Beziehung",
    "Gegensatz-Paare": "Beziehung",
    "Altersunterschied Beziehung": "Beziehung",
    "Große Alterslücke": "Beziehung",
    "Liebe Trotz Altersunterschied": "Beziehung",
    "Liebe Erkennen": "Psychologie",
    "Liebe und Sexualität": "Intimität",
    "Unterschiedliche Weltanschauungen Beziehung": "Konflikte",
    "Umstellung": "Neuanfang",
    "Überanalyse": "Psychologie",
    "Kindheit": "Psychologie",
    "Emotionale Intelligenz Lernen": "Psychologie",
    "Dating Minimalismus": "Dating",
    "Honeymoon Phase": "Beziehung",
    "Dating Dealbreaker Statistik": "Partnersuche",
    "Selbstschutz": "Sicherheit",
    "Plan B Haben": "Sicherheit",
    "Kreativität": "Date-Ideen",
    "Digitale Detox Gemeinsam": "Digital Detox",
    "Digitale Kommunikation": "Online-Dating",
    "Digitaler Detox": "Digital Detox",

    # Brand tags
    "MichVerlieben": "Dating-Apps",
    "OnlyDates69": "Dating-Apps",
    "Single69": "Dating-Apps",
    "Sex69": "Dating-Apps",
    "XLoves": "Dating-Apps",
    "WhatsMeet": "Dating-Apps",
    "Meta": "Digital Detox",
}

# These are the final ~35 core tags we want to keep
CORE_TAGS = {
    "Beziehung", "Dating", "Online-Dating", "Dating-Apps", "Flirten",
    "Erstes Date", "Date-Ideen", "Selbstliebe", "Psychologie", "Kommunikation",
    "Konflikte", "Vertrauen", "Red Flags", "Trennung", "Neuanfang",
    "Liebeskummer", "Eifersucht", "Fernbeziehung", "Familie", "Zusammenleben",
    "Hochzeit", "Gesundheit", "Heilung", "Intimität", "Finanzen",
    "Bindungstypen", "LGBTQ+", "Neurodiversität", "Digital Detox", "Sicherheit",
    "Partnersuche", "Kennenlernen", "Lokales Dating", "Lebensphasen",
    "Lifestyle", "Paartherapie", "Ratgeber", "Single-Leben", "Grenzen",
}


def map_tag(tag):
    """Map a tag to its core category."""
    tag = tag.strip()
    if tag in CORE_TAGS:
        return tag
    if tag in TAG_MAP:
        return TAG_MAP[tag]
    # If not mapped and not a core tag, try to find best match
    # Default: drop it (return None) - these are ultra-specific tags
    return None


def process_file(filepath):
    """Process a single markdown file and update its tags."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract frontmatter
    match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return False

    fm_text = match.group(1)
    rest = content[match.end():]

    try:
        fm = yaml.safe_load(fm_text)
    except:
        return False

    if not fm or 'tags' not in fm or not fm['tags']:
        return False

    old_tags = fm['tags']
    new_tags = set()

    for tag in old_tags:
        mapped = map_tag(str(tag).strip())
        if mapped:
            new_tags.add(mapped)

    # If no tags survived, assign based on most common
    if not new_tags:
        new_tags.add("Ratgeber")

    # Ensure at least 2 tags, max 5
    new_tags_list = sorted(new_tags)[:5]

    if new_tags_list == sorted(str(t).strip() for t in old_tags):
        return False  # No change needed

    # Rebuild the tags in YAML
    fm['tags'] = new_tags_list

    # Rebuild frontmatter preserving order
    # We'll do a targeted replacement of just the tags section
    tag_pattern = re.compile(r'(tags:\s*\n)((?:\s+-\s+.*\n?)*)', re.MULTILINE)
    tag_match = tag_pattern.search(fm_text)

    if tag_match:
        new_tag_lines = "tags:\n" + "".join(f'  - "{t}"\n' for t in new_tags_list)
        new_fm_text = fm_text[:tag_match.start()] + new_tag_lines + fm_text[tag_match.end():]
        new_content = f"---\n{new_fm_text}---{rest}"
    else:
        return False

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)

    return True


def main():
    blog_dir = "src/content/blog"
    files = [f for f in os.listdir(blog_dir) if f.endswith('.md')]

    changed = 0
    unchanged = 0
    errors = 0
    unmapped = set()

    for fname in sorted(files):
        filepath = os.path.join(blog_dir, fname)
        try:
            # First pass: collect unmapped tags
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
            if match:
                fm = yaml.safe_load(match.group(1))
                if fm and 'tags' in fm and fm['tags']:
                    for tag in fm['tags']:
                        t = str(tag).strip()
                        if t not in CORE_TAGS and t not in TAG_MAP:
                            unmapped.add(t)

            if process_file(filepath):
                changed += 1
            else:
                unchanged += 1
        except Exception as e:
            errors += 1
            print(f"ERROR: {fname}: {e}")

    print(f"\nResults: {changed} changed, {unchanged} unchanged, {errors} errors")
    if unmapped:
        print(f"\nUnmapped tags ({len(unmapped)}):")
        for t in sorted(unmapped):
            print(f"  - {t}")


if __name__ == "__main__":
    main()
